apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-pipeline
spec:
  resources:
    - name: git-repository
      type: git
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone-task
      resources:
        inputs:
          - name: git-repository
            resource: git-repository
      params:
        - name: repository
          value: https://github.com/simhasuraj/my_first_task
        - name: branch
          value: main
