apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: git-push-trigger
spec:
  bindings:
  - ref:
      apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      name: git-repository
    name: git-repository
  eventListeners:
  - name: git-listener
    template:
      name: git-push
      params:
      - name: repository
        description: The git repository to listen for push events on
      - name: branch
        description: The branch to listen for push events on
    serviceAccountName: git-listener
    resources:
    - git-repository
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: git-clone-task-run
    spec:
      taskRef:
        name: git-clone-task
      resources:
      - name: git-repository
        resourceRef:
          name: git-repository
      params:
      - name: repository
        value: $(bindings.git-repository.url)
      - name: branch
        value: $(bindings.git-repository.revision)
