apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: git-push-trigger
spec:
  bindings:
  - ref:
      apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      name: git-repository
    name: git-repository
  triggerTemplate:
    name: git-push
    params:
    - name: repository
      description: The git repository to listen for push events on
    - name: branch
      description: The branch to listen for push events on
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: git-clone-pipeline-run
    spec:
      pipelineRef:
        name: git-clone-pipeline
      resources:
      - name: git-repository
        resourceRef:
          name: git-repository
      params:
      - name: repository
        value: $(bindings.git-repository.url)
      - name: branch
        value: $(bindings.git-repository.revision)
