apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: git-manual-trigger
spec:
  bindings:
  - ref:
      apiVersion: tekton.dev/v1beta1
      kind: PipelineResource
      name: git-repository
    name: git-repository
  eventListeners:
  - name: git-manual-listener
    template:
      name: git-manual
      params:
      - name: repository
        description: The git repository to listen for manual events on
      - name: branch
        description: The branch to listen for manual events on
    serviceAccountName: git-manual-listener
    resources:
    - git-repository
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: git-clone-pipeline-run
    spec:
      pipelineRef:
        name: git-clone-pipeline
      resources:
      - name: git-repository
        resourceRef:
          name: git-repository
      params:
      - name: repository
        value: $(bindings.git-repository.url)
      - name: branch
        value: $(bindings.git-repository.revision)
